[build]
  publish = "public"  # Change this to your site output directory if different
  command = "echo 'No build command necessary for plain HTML site'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
